<?php
$boxData = [
    [
        'type' => 'primary',
        'textValue' => '1',
        'textLabel' => 'utilizatori',
        'textValueClass' => '<?= $tmpText ?>',
        'textLabelClass' => '<?= $tmpText ?>',
        'iconClass' => 'fa fa-users <?= $tmpText ?>',
        'linkLabel' => 'Detalii',
        'linkType' => 'light',
        'linkURL' => './utilizatori.htm',
    ],
    [
        'type' => 'success',
        'textValue' => '1',
        'textLabel' => 'profiluri',
        'textValueClass' => '<?= $tmpText ?>',
        'textLabelClass' => '<?= $tmpText ?>',
        'iconClass' => 'fa fa-users <?= $tmpText ?>',
        'linkLabel' => 'Detalii',
        'linkType' => 'light',
        'linkURL' => './utilizatori.htm',
    ],
    [
        'type' => 'warning',
        'textValue' => '1',
        'textLabel' => 'Bla Bla',
        'textValueClass' => '<?= $tmpText ?>',
        'textLabelClass' => '<?= $tmpText ?>',
        'iconClass' => 'fa fa-users <?= $tmpText ?>',
        'linkLabel' => 'Detalii',
        'linkType' => 'light',
        'linkURL' => './utilizatori.htm',
    ],
    [
        'type' => 'danger',
        'textValue' => '1',
        'textLabel' => 'utilozatori',
        'textValueClass' => '<?= $tmpText ?>',
        'textLabelClass' => '<?= $tmpText ?>',
        'iconClass' => 'fa fa-users <?= $tmpText ?>',
        'linkLabel' => 'Detalii',
        'linkType' => 'light',
        'linkURL' => './utilizatori.htm',
    ],
];
