<?php

$boxData = [
    [
        'type' => 'primary',
        'textValue' => '1',
        'textLabel' => 'utilizatori',
        'textValueClass' => 'text-white',
        'textLabelClass' => 'text-white',
        'iconClass' => 'fa fa-users text-white',
        'linkLabel' => 'Detalii',
        'linkType' => 'light',
        'linkURL' => './tabel-utilizatori.htm',
    ],
    [
        'type' => 'success',
        'textValue' => '1',
        'textLabel' => 'profiluri',
        'textValueClass' => 'text-white',
        'textLabelClass' => 'text-white',
        'iconClass' => 'fa fa-users text-white',
        'linkLabel' => 'Detalii',
        'linkType' => 'light',
        'linkURL' => './tabel-utilizatori.htm',
    ],
    [
        'type' => 'warning',
        'textValue' => '1',
        'textLabel' => 'Bla Bla',
        'textValueClass' => 'text-white',
        'textLabelClass' => 'text-white',
        'iconClass' => 'fa fa-users text-white',
        'linkLabel' => 'Detalii',
        'linkType' => 'light',
        'linkURL' => './tabel-utilizatori.htm',
    ],
    [
        'type' => 'danger',
        'textValue' => '1',
        'textLabel' => 'utilozatori',
        'textValueClass' => 'text-white',
        'textLabelClass' => 'text-white',
        'iconClass' => 'fa fa-users text-white',
        'linkLabel' => 'Detalii',
        'linkType' => 'light',
        'linkURL' => './tabel-utilizatori.htm',
    ],
];
