<?php 
    $tabel="awesomes_table";
  
    $fields=array(
        'bool0'=>array(
            'name'=>"B1",
            'type'=>'awesomecase',
            'template'=>'BoolCheck',
        ),
        'bool1'=>array(
            'name'=>"B2",
            'type'=>'awesomecase',
            'template'=>'BoolSquareCheck',
        ),
        'bool2'=>array(
            'name'=>"B3",
            'type'=>'awesomecase',
            'template'=>'BoolCircleCheck',
        ),
        'bool3'=>array(
            'name'=>"B4",
            'type'=>'awesomecase',
            'template'=>'BoolSquareCheckAlt',
        ),
        'bool4'=>array(
            'name'=>"B5",
            'type'=>'awesomecase',
            'template'=>'BoolEye',
        ),
        'bool5'=>array(
            'name'=>"B6",
            'type'=>'awesomecase',
            'template'=>'BoolEyeAlt',
        ),
        'bool6'=>array(
            'name'=>"B7",
            'type'=>'awesomecase',
            'template'=>'BoolCircle',
        ),
        'bool7'=>array(
            'name'=>"B8",
            'type'=>'awesomecase',
            'template'=>'BoolStar',
        ),
        'bool8'=>array(
            'name'=>"B9",
            'type'=>'awesomecase',
            'template'=>'BoolCheck',
        ),
        'bool9'=>array(
            'name'=>"B10",
            'type'=>'awesomecase',
            'template'=>'BoolCheck',
        ),
        'yesno0'=>array(
            'name'=>"YN1",
            'type'=>'awesomecase',
            'template'=>'YesNoCheck',
        ),
        'yesno1'=>array(
            'name'=>"YN2",
            'type'=>'awesomecase',
            'template'=>'YesNoSquareCheck',
        ),
        'yesno2'=>array(
            'name'=>"YN3",
            'type'=>'awesomecase',
            'template'=>'YesNoCircleCheck',
        ),
        'yesno3'=>array(
            'name'=>"YN4",
            'type'=>'awesomecase',
            'template'=>'YesNoSquareCheckAlt',
        ),
        'yesno4'=>array(
            'name'=>"YN5",
            'type'=>'awesomecase',
            'template'=>'YesNoEye',
        ),
        'yesno5'=>array(
            'name'=>"YN6",
            'type'=>'awesomecase',
            'template'=>'YesNoEyeAlt',
        ),
        'yesno6'=>array(
            'name'=>"YN7",
            'type'=>'awesomecase',
            'template'=>'YesNoCircle',
        ),
        'yesno7'=>array(
            'name'=>"YN8",
            'type'=>'awesomecase',
            'template'=>'YesNoStar',
        ),
        'yesno8'=>array(
            'name'=>"YN9",
            'type'=>'awesomecase',
            'template'=>'YesNoSwitch',
        ),
        'yesno9'=>array(
            'name'=>"YN10",
            'type'=>'awesomecase',
            'template'=>'YesNoSquareCheck',
            'fatype'=>'r,r'
        ),
        'yesnocancel'=>array(
            'name'=>"YNC",
            'type'=>'awesomecase',            
            'values'=>array('Y','N','C'),
            'chars'=>array('bell','bell-slash', 'ban'),
            'colors'=>array('#090','#900','#990'),
            'fatype'=>'r,r,'            
        ),
        'cars'=>array(
            'name'=>"Cars",
            'values'=>'A,B,C,D,E,F,G,H,I,J,K,L,M,N',
            'chars'=>'bicycle,bus-alt,car,motorcycle,car-side,fighter-jet,helicopter,plane,rocket,ship,shuttle-van,subway,truck-pickup,truck-monster',
            'type'=>'awesomecase',
        ),
        'chess'=>array(
            'name'=>"Chess",
            'type'=>'awesomecase',
            'values'=>array(0,1,2,3,4,5),
            'chars'=>array('chess-pawn', 'chess-rook', 'chess-knight', 'chess-bishop', 'chess-king', 'chess-queen'),
            'colors'=>array('#9B3219','#9B3219','#9B3219','#9B3219','#9B3219','#9B3219'),
        ),
        'files'=>array(
            'name'=>"Files",
            'type'=>'awesomecase',
            'values'=>'word,video,powerpoint,pdf,image,excel,code,audio,archive,alt',
            'chars'=>'file-word,file-video,file-powerpoint,file-pdf,file-image,file-excel,file-code,file-audio,file-archive,file-alt',
        ),
        
    );
    
    $addfields=array(
    );
    
    $title="AwesomeCase examples";

    $specials=array();

    $stitles=array(
    );

    $fontawesome=array(
    );

?>